title: CQ's Blog
email: cjw1115@hotmail.com
description: 杂货市场
url: "https://cjw1115.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cjw1115

theme: minima

plugins:
  - jekyll-feed

header_pages:
  - product/index.md
  - PrivacyPolicy/index.md
  - about.markdown